# Generated by Django 3.0.1 on 2020-02-10 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='宠物类型')),
            ],
        ),
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='宠物姓名')),
                ('pet_img', models.ImageField(default='pet_back/product-4.jpg', upload_to='pet_back/pet_img/%Y/%m', verbose_name='宠物图片')),
                ('intro', models.CharField(default='', max_length=256, verbose_name='简介')),
                ('contact_way', models.CharField(default='', max_length=256, verbose_name='联系方式')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='阅读量')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petback.PetCategory', verbose_name='宠物分类')),
            ],
            options={
                'verbose_name': '遗失宠物',
                'verbose_name_plural': '遗失宠物',
            },
        ),
    ]
