# Generated by Django 3.0.1 on 2020-02-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '宠物类型', 'verbose_name_plural': '宠物类型'},
        ),
    ]
