# Generated by Django 3.0.1 on 2020-02-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostpet',
            options={'ordering': ['-created_time'], 'verbose_name': '遗失宠物', 'verbose_name_plural': '遗失宠物'},
        ),
        migrations.AlterModelOptions(
            name='petcategory',
            options={'verbose_name': '宠物类型', 'verbose_name_plural': '宠物类型'},
        ),
    ]
