# Generated by Django 3.0.1 on 2020-02-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petback', '0002_auto_20200213_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='宠物类型')),
            ],
            options={
                'verbose_name': '宠物类型',
                'verbose_name_plural': '宠物类型',
            },
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petback.PetCategory', verbose_name='宠物分类'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
