# Generated by Django 3.0.1 on 2020-02-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20180311_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='province',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='signer_name',
        ),
        migrations.DeleteModel(
            name='UserLeavingMessage',
        ),
    ]
