# Generated by Django 3.0 on 2020-01-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petblog', '0002_auto_20200120_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='阅读量'),
        ),
    ]
