# Generated by Django 3.0.1 on 2020-02-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='摘要'),
        ),
    ]
