# Generated by Django 3.0.1 on 2020-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0002_science_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='science_img',
            field=models.ImageField(default='science/product-9.jpg', upload_to='science/science_img/%Y/%m', verbose_name='科普图片'),
        ),
    ]
