# Generated by Django 3.0 on 2020-02-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='product',
            name='intro',
            field=models.CharField(default='', max_length=256, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0, verbose_name='销量'),
        ),
    ]
