# Generated by Django 3.0 on 2020-02-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0002_auto_20200202_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0, verbose_name='原单价'),
        ),
    ]
