# Generated by Django 3.0 on 2020-02-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0003_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(default='petblog/img/product/product-4.jpg', upload_to='product/main_img/%Y/%m', verbose_name='商品主图'),
        ),
    ]
