# Generated by Django 3.0 on 2020-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0006_auto_20200202_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(default='assets/img/product/product-4.jpg', upload_to='static/assets/img/product/main_img/%Y/%m', verbose_name='商品主图'),
        ),
    ]
