# Generated by Django 3.0 on 2020-02-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0007_auto_20200202_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(default='product/product-4.jpg', upload_to='product/main_img/%Y/%m', verbose_name='商品主图'),
        ),
        migrations.AlterField(
            model_name='propic',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m', verbose_name='商品图'),
        ),
    ]
